name: spring-security-authorization

services:
  open-fga:
    image: openfga/openfga
    ports:
      - target: 9000
        published: 9000
      - target: 3000
        published: 3000
    command:
      - run
    environment:
      OPENFGA_HTTP_ADDR: 0.0.0.0:9000
  dex:
    image: "dexidp/dex:v2.37.0"
    ports:
      - target: 5556
        published: 5556
    configs:
      - source: dex_config
        target: /opt/config/dex.yml
    command:
      - dex
      - serve
      - /opt/config/dex.yml

configs:
  dex_config:
    content: |
      issuer: "http://localhost:5556"
      storage:
        type: sqlite3
        config:
          file: /etc/dex/dex.db
      web:
        http: 0.0.0.0:5556
      staticClients:
        - id: dex-client-id
          redirectURIs:
            - "http://localhost:8080/login/oauth2/code/dex"
            - "http://127.0.0.1:8080/login/oauth2/code/dex"
          name: 'Base application'
          secret: dex-client-secret
          grant_types:
            - authorization_code
      enablePasswordDB: true
      staticPasswords:
        - email: "admin@example.com"
          hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # "password"
          username: "user"
          userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
        - email: "carol@corp.example.com"
          hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # "password"
          username: "carol"
          userID: "800d74b3-e778-436f-8a9c-2b2cb9c87978"